### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by consuelita** [ask-fm/AFMActionSheet#15]
Any plans to update this for Swift 3?

**Comment by karpelcevs** [comment]
@consuelita most certainly! And now that we have a first request for it, we'll get to it faster :)
Can't promise, but I think next week sounds like a good time to do it.

**Comment by alesker** [comment]
@consuelita Update to Swift 3 comes with release [2.0.0](https://github.com/ask-fm/AFMActionSheet/releases/tag/2.0.0) which was just, well, released. :)
